# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 24678`
      export PORT=3000
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - "svelte.svelte-vscode"
    - "bradlc.vscode-tailwindcss"